--USUARIOS
INSERT INTO FASA.USUARIO (NOMBRE_USUARIO, EMAIL, PASSWORD, ROL) 
	VALUES ('rubengg', 'ruben@ruben.com', 'ruben', 'ANALISTA');

INSERT INTO FASA.USUARIO (NOMBRE_USUARIO, EMAIL, PASSWORD, ROL) 
	VALUES ('jesus', 'jesu@jesu.com', 'jesu', 'AUTOREGISTRADO');

INSERT INTO FASA.USUARIO_AUTO (ID, NOMBRE, APELLIDOS, DOMICILIO, CIUDAD, EDAD, SEXO) 
	VALUES (2, 'Jesus', 'Moreno', 'Calle Carretas', 'Malaga', 8, 'MASCULINO');

INSERT INTO FASA.USUARIO (NOMBRE_USUARIO, EMAIL, PASSWORD, ROL) 
VALUES ('egoncillo', 'egon@egon.com', 'egon', 'ADMINISTRADOR');

INSERT INTO FASA.USUARIO (NOMBRE_USUARIO, EMAIL, PASSWORD, ROL) 
VALUES ('paco', 'paco@paco.com', 'paco', 'TELEOPERADOR');

INSERT INTO FASA.USUARIO (NOMBRE_USUARIO, EMAIL, PASSWORD, ROL) 
	VALUES ('lusi', 'lusi@lusi.com', 'lusi', 'TELEOPERADOR');


--EVENTOS
--PROXIMO
INSERT INTO FASA.EVENTO (TITULO, DESCRIPCION, FECHA_EVENTO, FECHA_LIMITE, PRECIO, AFORO, LIMITE_USUARIO, N_FILAS, N_ASIENTOS_FILA) 
	VALUES ('WEEKEND', 'Festival en Torre del Mar', '2021-07-21', '2021-07-20', 50.0, 40, 4, 4, 10);

--REALIZADO
INSERT INTO FASA.EVENTO (TITULO, DESCRIPCION, FECHA_EVENTO, FECHA_LIMITE, PRECIO, AFORO, LIMITE_USUARIO, N_FILAS, N_ASIENTOS_FILA) 
	VALUES ('Melendi', 'Concierto', '2021-05-17', '2021-05-15', 20.0, 20, 2, 2, 10);

INSERT INTO FASA.ETIQUETA (ETIQUETA, ID_EVENTO) 
	VALUES ('FESTIVAL', 1);

INSERT INTO FASA.ETIQUETA (ETIQUETA, ID_EVENTO) 
	VALUES ('CONCIERTO', 1);

INSERT INTO FASA.CHAT (ID_USUARIO, ID_TELEOPERADOR) 
	VALUES (2, 3);

INSERT INTO FASA.MENSAJE (ID_CHAT, ID_EMISOR, TEXTO) 
	VALUES (1, 2, 'nocena');

