CREATE TABLE USUARIO (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRE_USUARIO VARCHAR(50) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL, 
	PASSWORD VARCHAR(20) NOT NULL,
	--ROL ENUM('ADMINISTRADOR','CREADOR', 'AUTOREGISTRADO', 'TELEOPERADOR', 'ANALISTA') NOT NULL, 
	ROL VARCHAR(15)
               CHECK( ROL IN('ADMINISTRADOR','CREADOR', 'AUTOREGISTRADO', 'TELEOPERADOR', 'ANALISTA') ) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE USUARIO_AUTO (
	ID INTEGER,
	NOMBRE VARCHAR(50) NOT NULL, 
	APELLIDOS VARCHAR(50) NOT NULL, 
	DOMICILIO VARCHAR(50),
	CIUDAD VARCHAR(20), 
	EDAD INTEGER,
	--SEXO ENUM('MASCULINO','FEMENINO'), 
	SEXO VARCHAR(15)
               CHECK( SEXO IN('MASCULINO','FEMENINO') ) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES USUARIO (ID)
);

CREATE TABLE EVENTO (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TITULO VARCHAR(20) NOT NULL, 
	DESCRIPCION VARCHAR(200) NOT NULL, 
	FECHA_EVENTO DATE, 
	FECHA_LIMITE DATE, 
	PRECIO DOUBLE, 
	AFORO INTEGER, 
	LIMITE_USUARIO INTEGER, 
	N_FILAS INTEGER, 
	N_ASIENTOS_FILA INTEGER, 
	PRIMARY KEY (ID)
);

CREATE TABLE ENTRADA (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ID_USUARIO INTEGER, 
	ID_EVENTO INTEGER, 
	FILA INTEGER, 
        ASIENTO INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
	FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO (ID)
);

CREATE TABLE CHAT (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), --cambiar a fecha creacion
	ID_USUARIO INTEGER, 
	ID_TELEOPERADOR INTEGER,
	PRIMARY KEY (ID), 
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
	FOREIGN KEY (ID_TELEOPERADOR) REFERENCES USUARIO (ID)
);

CREATE TABLE MENSAJE (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), --cambiar a hora+dia
	ID_CHAT INTEGER,
    ID_EMISOR INTEGER,
	TEXTO VARCHAR(200), 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_CHAT) REFERENCES CHAT (ID),
        FOREIGN KEY (ID_EMISOR) REFERENCES USUARIO (ID)
);

CREATE TABLE ETIQUETA (
	ETIQUETA VARCHAR(50) NOT NULL,
        ID_EVENTO INTEGER,
	PRIMARY KEY (ETIQUETA),
        FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO (ID)
);